name: ubuntu Build
on:
  #监听push操作
  push:
    branches:
      - master # 这里只配置了main分支，所以只有推送main分支才会触发以下任务
    paths-ignore:
        - '**.md' # 排除只修改md文件
    tags:
        - 'v*' # 只有版本更新才触发
  pull_request:
    paths-ignore:
       - '**.md'
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 官方action，将代码拉取到虚拟机
      - name: Checkout  ️ 
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install   # 安装依赖、打包，如果提前已打包好无需这一步
        run: |
          npm install
      - name: Build   # 安装依赖、打包，如果提前已打包好无需这一步
        run: |
          npm run build 
      - name: LS
        run: ls 
      - name: Zip the Build
        run: zip -r test ./dist/ 
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.01
          name: Release0.01
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            test.zip
            LICENSE 